apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  name: finn11-kafka-connect-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: finn11
    server: https://kubernetes.default.svc
  project: finn11
  source:
    path: lab3-4/services/kconnect
    repoURL: https://github.com/jbcodeforce/eda-tech-academy.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
