apiVersion: batch/v1
kind: Job
metadata:
  name: cpsecret
  namespace: finn11
spec:
  template:
    metadata:
      name: cpsecret
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - "if [ -z \"$(kubectl get secret ibm-entitlement-key -n finn11 | grep found)\" ]; \
          then kubectl get secret ibm-entitlement-key -n cp4i-eventstreams -o json \
          | jq -r '.metadata.namespace=\"finn11\"' \
          | jq 'del(.metadata.uid, .metadata.selfLink, .metadata.ownerReferences, .metadata.resourceVersion, .metadata.creationTimestamp)'  \
          | kubectl apply -n finn11 -f - ;\
          else echo already_created; fi"
        image: bitnami/kubectl
        name: copysecret
      restartPolicy: Never
      serviceAccountName: rt-inv-job-sa
